# Generated by Django 5.0.2 on 2024-05-08 10:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auth_api", "0001_add_feedback_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[],
            options={
                "verbose_name": "Teams",
                "verbose_name_plural": "Teams",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
