# Generated by Django 5.1 on 2024-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterModelOptions(
            name="roles",
            options={"verbose_name": "Roles", "verbose_name_plural": "Roles"},
        ),
    ]
