# Generated by Django 5.1 on 2024-08-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0003_company_team_alter_roles_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.company",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="company",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.company",
            ),
            preserve_default=False,
        ),
    ]
