# Generated by Django 5.1 on 2024-08-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0004_customuser_company_customuser_team_team_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth_api.company"
            ),
        ),
    ]
