# Generated by Django 5.1 on 2024-08-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0005_alter_team_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.team",
            ),
        ),
    ]
