# Generated by Django 5.0.2 on 2024-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_add_created_at_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="koerperliche_einschraenkung",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="motivation",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="muskulaere_erschoepfung",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="schlaf",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="stress",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
    ]
