# Generated by Django 5.0.2 on 2024-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
