# Generated by Django 5.1 on 2024-08-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0006_alter_customuser_company_alter_customuser_team"),
        ("feedback", "0004_alter_feedback_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.team",
            ),
            preserve_default=False,
        ),
    ]
