# Generated by Django 5.1 on 2024-08-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0006_alter_customuser_company_alter_customuser_team"),
        ("feedback", "0005_feedback_company_feedback_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.company",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.team",
            ),
        ),
    ]
