# Generated by Django 5.1 on 2024-08-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0006_alter_customuser_company_alter_customuser_team"),
        ("feedback", "0006_alter_feedback_company_alter_feedback_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("head", models.BooleanField()),
                ("neck", models.BooleanField()),
                ("leftShoulder", models.BooleanField()),
                ("leftUpperArm", models.BooleanField()),
                ("leftElbow", models.BooleanField()),
                ("leftLowerArm", models.BooleanField()),
                ("leftHand", models.BooleanField()),
                ("rightShoulder", models.BooleanField()),
                ("rightUpperArm", models.BooleanField()),
                ("rightElbow", models.BooleanField()),
                ("rightLowerArm", models.BooleanField()),
                ("rightHand", models.BooleanField()),
                ("upperBody", models.BooleanField()),
                ("lowerBody", models.BooleanField()),
                ("leftUpperLeg", models.BooleanField()),
                ("leftKnee", models.BooleanField()),
                ("leftLowerLeg", models.BooleanField()),
                ("leftFoot", models.BooleanField()),
                ("rightUpperLeg", models.BooleanField()),
                ("rightKnee", models.BooleanField()),
                ("rightLowerLeg", models.BooleanField()),
                ("rightFoot", models.BooleanField()),
                ("abdomen", models.BooleanField()),
                ("vestibular", models.BooleanField()),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_api.company",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_api.team",
                    ),
                ),
            ],
        ),
    ]
