# Generated by Django 5.1 on 2024-08-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_pain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="created_at",
        ),
    ]
