# Generated by Django 5.1 on 2024-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_remove_feedback_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
