# Generated by Django 5.1 on 2024-08-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_feedback_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
